apiVersion: apps/v1
kind: Deployment
metadata:
  name: christiania
  labels:
    app: christiania
spec:
  replicas: 3
  selector:
    matchLabels:
      app: christiania
  template:
    metadata:
      labels:
        app: christiania
    spec:
      containers:
      - name: christiania
        image: christiania:0.0.1
        ports:
        - containerPort: 5000